version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8086:8080"
    volumes:
      - ./web:/app
      - ./shared:/app/shared
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - ./bot:/app
      - ./shared:/app/shared
    environment:
      - BOT_TOKEN=7882564456:AAEAV2hjSnVHAdz384XcvA7REjBfabNWst0  # imposta anche il tuo token in locale oppure in un .env
    depends_on:
      - web
    restart: unless-stopped
